Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        //для доступа к нашей доменной модели (доменным объектам).
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.ServiceItems.GetServiceItems());
        }
        public IActionResult TwoPanel()
        {
            return View(dataManager.VehicleFleet.GetVehicleFleet());
        }
    }
}

Areas/Admin/Controllers/ServiceItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Areas/Admin/Controllers/TextFieldsController.cs
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;
using Microsoft.AspNetCore.Mvc;
using System;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

Areas/Admin/Controllers/VehicleFleetItemsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;
using System;
using System.IO;



namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VehicleFleetItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public VehicleFleetItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new VehicleFleetItem() : dataManager.VehicleFleet.GetVehicleFleetById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(VehicleFleetItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.VehicleFleet.SaveVehicleFleet(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.VehicleFleet.DeleteVehicleFleet(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        //конструктор
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }
        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
        public IActionResult Garage(Guid id)
        {
            if (id != default)
            {
                return View("ShowCars", dataManager.VehicleFleet.GetVehicleFleetById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageVehicleFleet");
            return View(dataManager.VehicleFleet.GetVehicleFleet());
        }

        public IActionResult Company_achievements()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageCompanyAchievements"));
        }
    }
}

Controllers/ServicesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager; 
        //конструктор
        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }

        //вкладка Автопарк
        /*
        public IActionResult Garage(Guid id)
        {
            if (id != default)
            {
                return View("ShowCars", dataManager.VehicleFleet.GetVehicleFleetById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageVehicleFleet");
            return View(dataManager.VehicleFleet.GetVehicleFleet());
        }
        */
    }
}

Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div>
        <br>
        <h3>Автопарк</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="Home" asp-action="TwoPanel">Панель</a>
        </div>
        
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageVehicleFleet">Автопарк</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageCompanyAchievements">Достижения</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

Areas/Admin/Views/Home/TwoPanel.cshtml
@model IQueryable<VehicleFleetItem>
@{
    string strTitle = "Панель";
    ViewBag.Title = strTitle;
}

<div>
    <br>
    <h3>Автопарк</h3>
    <div class="div-box">
        <a asp-area="Admin" asp-controller="VehicleFleetItems" asp-action="Edit" asp-route-id="">Добавить автомобиль</a>
    </div>
    @if (Model.Any())
    {
        <div>
            @foreach (VehicleFleetItem entity in Model)
            {
                <div>
                    <a asp-area="Admin" asp-controller="VehicleFleetItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                    |
                    <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="VehicleFleetItems" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@entity.Id">
                        <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                    </form>
                    |
                    <a asp-area="" asp-controller="Home" asp-action="Garage" asp-route-id="@entity.Id">
                        @($"{entity.Title}")
                    </a>
                </div>
            }
        </div>
    }
</div>